name: Deploy
on:
  push: 
    branch: 
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout
      - uses: tgwarren/membersContactDirectory
      with: 
        branch: "master"
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "troop2012"
        heroku_email: twarre30@gmail.com
